config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  concern :commentable do
    resources :comments, except: [:index, :show]
  end
  concern :imageable do
    resources :images, except: [:index, :show]
  end

  resources :users, only: [:new, :create]
  resources :profile, controller: :users, as: :user, except: [:new, :create], concerns: :imageable
  get "groups/:group_id/invite" => 'groups#send_invite', as: :send_invite
  scope module: 'jefe' do
    resources :groups, except: [:index, :new, :create, :show]
  end
  resources :groups, concerns: :imageable, only: [:show, :new, :create] do
    resources :posts, only: :index
    resources :snippets, only: :index
    resources :users, only: [:index, :show] do
      resources :posts, concerns: :commentable
      resources :snippets, concerns: :commentable
    end
  end
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
	
  belongs_to :creator, class_name: "User"
  belongs_to :group
  has_many :comments, as: :commentable
  has_one :image, as: :imageable
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
	before_action :login_required
	before_action :group_user_and_snippet_objects

	def index
		@user_snippets = @user.snippets.order('updated_at DESC')
	end

	def show
		@snippet = @group.members.find(@user.id).snippets.find(@snippet.id)
		@image = @snippet.image if @snippet.image
		@comments = @snippet.comments.order('updated_at DESC') if !@snippet.comments.empty? 
	end

	def new
		@snippet = Snippet.new	
		session[:return_to] = request.referer
	end

	def create
		snippet = @user.snippets.new(snippet_params)
		snippet.group_id = @group.id
		picture = params[:snippet][:picture]
		if snippet.save
			snippet.image = Image.create(picture: picture) unless !picture
			redirect_to session.delete(:return_to)
			# Send Notification
			GroupMailer.group_snippet_notifications(snippet.group, snippet)
		else
			render 'form'
		end
	end

	def edit	
		is_current_user?
		session[:return_to] = request.referer
	end

	def update

		if params[:snippet][:picture]
			image = Image.new(picture: params[:snippet][:picture])
			@snippet.image = image
		end
		@snippet.update_attributes(snippet_params)
		redirect_to session.delete(:return_to)
	end

	def destroy
		@snippet.destroy
		redirect_to :back
	end

	def group_user_and_snippet_objects
		@snippet = Snippet.find(params[:id]) unless %w[index new create].include?(params[:action])
		@group = Group.find(params[:group_id])
		@user = User.find(params[:user_id])
	end

	def is_current_user?
		redirect_to group_user_snippets_path unless current_user.id == @user.id
	end

	def login_required
	  redirect_to new_user_session_path unless current_user
	end
	
	private 
		def snippet_params
			params.require(:snippet).permit(:content)
		end
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/snippets/_form.html.erb
<div id="timeline">
	<%= form_for [@group, @user, @snippet] do |f| %>
		<p>
		  <%= f.file_field :picture %>
	  </p>
		<p>
			<%= f.label :content %>
			<%= f.text_area :content %>
		</p>
		<%= f.submit %>
	<% end %>
</div>

app/views/snippets/_snippet.html.erb
<div class="snippet">
<h3>Snippet</h3>
<h5><%=User.find_by_id(snippet.creator_id).first_name%>  <%=User.find_by_id(snippet.creator_id).last_name%> - <%= snippet.created_at.strftime("%B, %d, %Y") %></h5>
<p><%=snippet.content%></p>
<% unless snippet.comments.empty? %>
<% snippet.comments.each do |comment|	%>
<div class="comment">
	<h5><%=User.find_by_id(comment.creator_id).first_name%>  <%=User.find_by_id(comment.creator_id).last_name%> - <%= comment.created_at.strftime("%B, %d, %Y") %></h5>
	<p><%= comment.content %></p>
</div>
<% end %>
<% end %> 
</div>

app/views/snippets/edit.html.erb
edit.html.erb

app/views/snippets/index.html.erb
<div id="timeline">
<h2><%= @user.first_name%>  <%=@user.last_name%>'s snippets</h2>
<% if current_user.id == @user.id %>
	<button><%= link_to "Snip", new_group_user_snippet_path %></button>
<% end %>
<% @user_snippets.each do |snippet| %>
	<%= link_to [snippet.group, snippet.creator, snippet] do %>
		<div class="snippet">
			<h5><%= snippet.created_at.strftime("%B, %d, %Y") %></h5>
				<% if snippet.image %>	
						<img src="<%= snippet.image.picture %>"> 
				<% end %>
				<p><%=snippet.content%></p>
			<% unless snippet.comments.empty? %>
				<% snippet.comments.each do |comment|	%>
					<div class="comment">
						<h5><%=User.find_by_id(comment.creator_id).first_name%>  <%=User.find_by_id(comment.creator_id).last_name%> - <%= comment.created_at.strftime("%B, %d, %Y") %></h5>
						<p><%= comment.content %></p>
						<% if current_user == comment.creator %>
								<div class='commentEditing'>
									<%= link_to "Edit", edit_group_user_snippet_comment_path(snippet.group, snippet.creator, snippet, comment) %>
									<%= link_to "Delete", [snippet.group, snippet.creator, snippet, comment], method: :delete %>
								</div>
						<% end %>
					</div>
				<% end %>
			<% end %> 
			<br>
			<div class="editing">
				<button><%= link_to "Comment", new_group_user_snippet_comment_path(snippet.group, snippet.creator, snippet)%></button>
				<% if current_user.id == snippet.creator_id %>
					<button><%= link_to "Edit", edit_group_user_snippet_path(snippet.group, snippet.creator, snippet)%></button>
					<button><%= link_to "Delete", [snippet.group, snippet.creator, snippet], method: :delete %></button>
				<% end %>
			</div>
		</div>
	<% end %>
<% end %>
</div>

app/views/snippets/new.html.erb
new.html.erb

app/views/snippets/show.html.erb
<div id="timeline">
	<h2><%=@snippet.creator.first_name%>  <%=@snippet.creator.last_name%> - <%= @snippet.created_at.strftime("%B %d, %Y") %></h2>
	<div class="snippet">
		<% if @image %>
			<img src="<%= @image.picture %>">
		<% end %>
		<p> <%= @snippet.content %></p>
		<% if @comments %>
			<% @comments.each do |comment| %>
				<div class="comment">
					<h5><%=User.find_by_id(comment.creator_id).first_name%>  <%=User.find_by_id(comment.creator_id).last_name%> - <%= comment.created_at.strftime("%B, %d, %Y") %></h5>
					<%= comment.content %>
					<% if current_user.id == comment.creator_id %>
						<%= link_to "Edit", edit_group_user_snippet_comment_path(@snippet.group, @snippet.creator, @snippet, comment) %>
						<%= link_to "Delete", [@snippet.group, @snippet.creator, @snippet, comment], method: :delete %>
					<% end %>
				</div>
			<% end %>
		<% end %>
		<br>
		<div class="editing">
			<button><%= link_to "Comment", new_group_user_snippet_comment_path(@snippet.group, @snippet.creator, @snippet)%></button>
			<% if current_user.id == @snippet.creator_id %>
				<button><%= link_to "Edit", edit_group_user_snippet_path%></button>
				<button><%= link_to "Delete", [@snippet.group, @snippet.creator, @snippet], method: :delete %></button>
			<% end %>
		</div>
	</div>
	<%= link_to "More snippets from this user", group_user_snippets_path %>
	<%= link_to "Back to group", "/groups/#{@snippet.group_id}" %>
</div>