config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  concern :commentable do
    resources :comments, except: [:index, :show]
  end
  concern :imageable do
    resources :images, except: [:index, :show]
  end

  resources :users, only: [:new, :create]
  resources :profile, controller: :users, as: :user, except: [:new, :create], concerns: :imageable
  get "groups/:group_id/invite" => 'groups#send_invite', as: :send_invite
  scope module: 'jefe' do
    resources :groups, except: [:index, :new, :create, :show]
  end
  resources :groups, concerns: :imageable, only: [:show, :new, :create] do
    resources :posts, only: :index
    resources :snippets, only: :index
    resources :users, only: [:index, :show] do
      resources :posts, concerns: :commentable
      resources :snippets, concerns: :commentable
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :image, as: :imageable
  has_many :memberships, foreign_key: :member_id
  has_many :groups, through: :memberships
  has_many :managed_groups, foreign_key: :jefe_id, class_name: "Group"
  has_many :posts, foreign_key: :creator_id
  has_many :snippets, foreign_key: :creator_id
  has_many :comments, foreign_key: :creator_id

  include BCrypt

  def password
    @password ||= Password.new(password_digest)
  end

  def password=(pass)
    @password = Password.create(pass)
    self.password_digest = @password
  end

  def self.authenticate(email, password)
    user = User.find_by_email(email)
    return user if user && (user.password == password)
    nil
  end

  # def authenticate(password)
  #   user = self
  #   return user if user && (user.password == password)
  #   nil
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def index
    
	end

	def show
		@user = User.find(params[:id])
		@image = @user.image if @user.image
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		
		if params[:user][:picture]
			image = Image.new(picture: params[:user][:picture])
			@user.image = image
		end
		
		@user.update_attributes(user_params)
		redirect_to user_path
	end

	private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :current_location)
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_for(@user, url: user_path(@user)) do |user| %>
<%= user.label :first_name %>
<%= user.text_field :first_name %>
<br>
<%= user.label :last_name %>
<%= user.text_field :last_name %>
<br>
<%= user.label :email %>
<%= user.text_field :email %>
<br>
<%= user.label :new_password %>
<%= user.password_field :password %>
<br>
<%= user.label :new_password_confirmation %>
<%= user.password_field :password_confirmation %>
<br>
<%= user.label :current_location %>
<%= user.text_field :current_location %>
<br>
<%= user.submit %>
<% end %>

app/views/users/index.html.erb
<h1>Friendzone</h1>

app/views/users/show.html.erb
<!-- user GET  /profile/:id(.:format)  users#show -->

<div class="profile">
<br>
<% if @image %>
	<img id="profile_img" src="<%= @image.picture %>"> <br>
<% end %>
<h2><%= @user.first_name %> <%= @user.last_name %></h2>	
<ul class="profile_stats">
	<li><%= @user.email %></li>
	<li><%= @user.current_location %></li>
</ul>

<%= button_to 'Edit Profile', edit_user_url(@user), class: 'button', method: :get %>

<%= button_to 'Change Email/Password', edit_user_registration_url(@user), class: 'button', id: 'pw_button', method: :get %>

<%= button_to 'Create New Group', new_group_url(@user), class: 'button', method: :get %>

<h2>Memberships</h2>
<ul class="profile_stats">
	<% @user.groups.each do |group| %>
	<li><%= link_to group.name, group %><br><strong>Jefe:</strong> <%= group.jefe.first_name %> <%= group.jefe.last_name %></li>
	<br>
<% end %>
</ul>
</div>