config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  concern :commentable do
    resources :comments, except: [:index, :show]
  end
  concern :imageable do
    resources :images, except: [:index, :show]
  end

  resources :users, only: [:new, :create]
  resources :profile, controller: :users, as: :user, except: [:new, :create], concerns: :imageable
  get "groups/:group_id/invite" => 'groups#send_invite', as: :send_invite
  scope module: 'jefe' do
    resources :groups, except: [:index, :new, :create, :show]
  end
  resources :groups, concerns: :imageable, only: [:show, :new, :create] do
    resources :posts, only: :index
    resources :snippets, only: :index
    resources :users, only: [:index, :show] do
      resources :posts, concerns: :commentable
      resources :snippets, concerns: :commentable
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, class_name: "User"
  belongs_to :group
  has_many :comments, as: :commentable
  has_many :images, as: :imageable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :login_required
	before_action :group_user_and_post_objects

	def index
		@user_posts = @user.posts.order('updated_at DESC')
	end

	def show
		@post = Group.find(params[:group_id]).members.find(params[:user_id]).posts.find(params[:id])
		@images = @post.images if !@post.images.empty?
		@comments = @post.comments.order('updated_at DESC') if !@post.comments.empty?
	end

	def new
		@post = Post.new	
		session[:return_to] = request.referer
	end

	def create
		post = @user.posts.new(post_params)
		post.group_id = @group.id
		pictures = params[:post][:picture]
		if post.save
			pictures.each {|pic| post.images.create(picture: pic)} unless !pictures
			redirect_to session.delete(:return_to)
			# Send Notification
			GroupMailer.group_post_notifications(post.group, post)
		else
			render 'form'
		end
	end

	def edit	
		session[:return_to] = request.referer
		is_current_user?
	end

	def update
		@post.update_attributes(post_params)
		redirect_to session.delete(:return_to)
	end

	def destroy
		@post.destroy
		redirect_to :back
	end

	def group_user_and_post_objects
		@post = Post.find(params[:id]) if %w[edit update destroy].include?(params[:action])
		@group = Group.find(params[:group_id])
		@user = User.find(params[:user_id])
	end

	def is_current_user?
		redirect_to redirect_to session.delete(:return_to) unless current_user.id == @user.id
	end

	def login_required
	  redirect_to new_user_session_path unless current_user
	end
	
	private 
		def post_params
			params.require(:post).permit(:title, :content)
		end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [@group, @user, @post], :html => { :multipart => true } do |f| %>
  <p>
	  <%= f.file_field :picture, :multiple => true %>
  </p>
  <p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :content %>
		<%= f.text_area :content %>
	</p>
	<%= f.submit %>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
<h3><%=post.title%></h3>
<h5><%=User.find_by_id(post.creator_id).first_name%>  <%=User.find_by_id(post.creator_id).last_name%> - <%= post.created_at.strftime("%B, %d, %Y") %></h5>
<p><%=post.content%></p>
<% unless post.comments.empty? %>
<% post.comments.each do |comment|	%>
<div class="comment">
	<h5><%=User.find_by_id(comment.creator_id).first_name%>  <%=User.find_by_id(comment.creator_id).last_name%> - <%= comment.created_at.strftime("%B, %d, %Y") %></h5>
	<p><%= comment.content %></p>
</div>
<% end %>
<% end %> 
</div>

app/views/posts/edit.html.erb
edit.html.erb

app/views/posts/index.html.erb
<div id="timeline">
<h2><%= @user.first_name%>  <%=@user.last_name%>'s posts</h2>
	<% if current_user.id == @user.id %>
		<button><%= link_to "New Post", new_group_user_post_path %></button>
	<% end %>
<% @user_posts.each do |post| %>
	<%= link_to [post.group, post.creator, post] do %>
		<div class="post">
			<h3><%= post.title %></h3>
			<h5><%= post.created_at.strftime("%B, %d, %Y") %></h5>
				<% unless post.images.empty? %>
					<% post.images.each do |image| %>	
						<img src="<%= image.picture %>"> 
					<% end %>
				<% end %>
				<p><%=post.content%></p>
			<% unless post.comments.empty? %>
				<% post.comments.each do |comment|	%>
					<div class="comment">
						<h5><%=User.find_by_id(comment.creator_id).first_name%>  <%=User.find_by_id(comment.creator_id).last_name%> - <%= comment.created_at.strftime("%B, %d, %Y") %></h5>
						<p><%= comment.content %></p>
						<% if current_user == comment.creator %>
							<div class='commentEditing'>
								<%= link_to "Edit", edit_group_user_post_comment_path(post.group, post.creator, post, comment) %>
								<%= link_to "Delete", [post.group, post.creator, post, comment], method: :delete %>
							<% end %>
							</div>
					</div>
				<% end %>
			<% end %> 
			<div class="editing">
				<button><%= link_to "Comment", new_group_user_post_comment_path(post.group, post.creator, post)%></button>
				<% if current_user == post.creator %>
					<button><%= link_to "Edit", edit_group_user_post_path(post.group, post.creator, post) %></button>
					<button><%= link_to "Delete", [post.group, post.creator, post], method: :delete %></button>
				<% end %>
			</div>
		</div>
		<% end %>
		<br>
<% end %>
</div>

app/views/posts/new.html.erb
new.html.erb

app/views/posts/show.html.erb
<div id="timeline">
	<div class="post">
		<h1> <%= @post.title %> </h1>
		<h5><%=@post.creator.first_name%>  <%=@post.creator.last_name%> - <%= @post.created_at.strftime("%B %d, %Y") %></h5>
		<% if @images  %>
			<% @images.each do |image| %>
			<img src="<%= image.picture %>">
			<% end %>
		<% end %>
		<p> <%= @post.content %></p>
		<% if @comments %>
			<% @comments.each do |comment| %>
				<div class="comment">
					<h5><%=User.find_by_id(comment.creator_id).first_name%>  <%=User.find_by_id(comment.creator_id).last_name%> - <%= comment.created_at.strftime("%B, %d, %Y") %></h5>
					<%= comment.content %>
					<% if current_user == comment.creator %>
						<%= link_to "Edit", edit_group_user_post_comment_path(@post.group, @post.creator, @post, comment) %>
						<%= link_to "Delete", [@post.group, @post.creator, @post, comment], method: :delete %>
					<% end %>
				</div>
			<% end %>
		<% end %>
		<br>
		<div class="editing">
			<button><%= link_to "Comment", new_group_user_post_comment_path(@post.group, @post.creator, @post)%></button>
			<% if current_user == @post.creator %>
				<button><%= link_to "Edit", edit_group_user_post_path %></button>
				<button><%= link_to "Delete", [@post.group, @post.creator, @post], method: :delete %></button>
			<% end %>
		</div>
	</div>
	<br>
	<%= link_to "More posts from this user", group_user_posts_path %>   
	<%= link_to "Back to group", "/groups/#{@post.group_id}" %>
</div>